### ISSUE TITLE
Missing library bcrypt after clean install

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform-scripts#6]
```
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_application_authentication_manager/src/rapp_application_authentication_manager/application_authentication_node.py", line 24, in <module>
    import bcrypt
ImportError: No module named bcrypt
```

**Comment by etsardou** [comment]
Also `libffi-dev` must be installed before bcrypt

```
sudo apt-get install libffi-dev
sudo pip install bcrypt
```

**Comment by etsardou** [comment]
Also `sudo pip install passlib`

**Comment by athallas** [comment]
They are installed in script 13:

https://github.com/rapp-project/rapp-platform-scripts/blob/master/setup/13_authentication_setup.sh#L22

Maybe the setup wasn't successful. I'm leaving this open, until we figure out the problem.

**Comment by etsardou** [comment]
Actually I'm closing these issues and I'm adding a new one to test everything in a clean VM after all repos are synced in master branches
